/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.ipn.dbst.ui.prestamos;

import mx.ipn.dbst.controlador.PrestamoCon;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.ipn.dbst.model.*;
import mx.ipn.dbst.ui.Conexion;


/**
 *
 * @author angeldlr
 */
public class RealizarPrestamoView extends javax.swing.JFrame {
    
    private List<Sucursal> listSucursales;
    private List<Lector> listLectores;
    private List<Libro> listLibros;
    /**
     * Creates new form RealizarPrestamoView
     */
    public RealizarPrestamoView() {
        initComponents();
        setLocationRelativeTo(null);
        addSuc();
        addLectores();
        
    }
    private void addSuc(){
        PrestamoCon querySuc = new PrestamoCon();
        Conexion c = new Conexion();
        try {
            Connection con = c.crearConexion();
            listSucursales = querySuc.getSucursales(con);
        } catch (SQLException ex) {
            Logger.getLogger(RealizarPrestamoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i=0;i<listSucursales.size();i++)
            cbSucursales.addItem(listSucursales.get(i).getNombreSucursal());
    }
    private void addLectores(){
        PrestamoCon querySuc = new PrestamoCon();
        Conexion c = new Conexion();
        
        try {
            Connection con = c.crearConexion();
            listLectores = querySuc.getLectores(con);
        } catch (SQLException ex) {
            Logger.getLogger(RealizarPrestamoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i=0;i<listLectores.size();i++){
            int numL= listLectores.get(i).getNumTarjeta();
            String nom = listLectores.get(i).getNombre();
            cbLectores.addItem(nom+",Número de lector: "+numL);
        }
            
    }
    private void addLibros(){
        PrestamoCon querySuc = new PrestamoCon();
        Conexion c = new Conexion();
        
        try {
            Connection con = c.crearConexion();
            listLibros = querySuc.getLibrosSuc(con,listSucursales.get(cbSucursales.getSelectedIndex()).getIdSucursal());
        } catch (SQLException ex) {
            Logger.getLogger(RealizarPrestamoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbLibrosDisp.removeAllItems();
        for(int i=0;i<listLibros.size();i++)
            cbLibrosDisp.addItem(listLibros.get(i).getTitulo()+","+listLibros.get(i).getAutorLibro().getNombreAutor());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbSucursales = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbLectores = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbLibrosDisp = new javax.swing.JComboBox<>();
        btnAddPrestamo = new javax.swing.JButton();

        setTitle("AGREGAR PRESTAMOS");

        cbSucursales.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        cbSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSucursalesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        jLabel1.setText("Sucursal :");

        jLabel2.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        jLabel2.setText("Lector :");

        cbLectores.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        jLabel3.setText("Libros disponibles :");

        cbLibrosDisp.setMaximumSize(new java.awt.Dimension(37, 25));

        btnAddPrestamo.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        btnAddPrestamo.setText("Agregar prestamo");
        btnAddPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbLectores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbLibrosDisp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSucursales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLectores, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbLibrosDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(btnAddPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSucursalesActionPerformed
        // TODO add your handling code here:
        addLibros();
    }//GEN-LAST:event_cbSucursalesActionPerformed

    private void btnAddPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPrestamoActionPerformed
        Prestamo pr;
        String est = null;
        pr = new Prestamo(listLibros.get(cbLibrosDisp.getSelectedIndex()),listLectores.get(cbLectores.getSelectedIndex()),listSucursales.get(cbSucursales.getSelectedIndex()),null,null);
        PrestamoCon pres = new PrestamoCon();
        Conexion c = new Conexion();
        
        try {
            Connection con = c.crearConexion();
            est = pres.nuevoPrestamo(con, pr);
        } catch (SQLException ex) {
            Logger.getLogger(RealizarPrestamoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, est, "Estatus prestamo",JOptionPane.INFORMATION_MESSAGE);
        System.out.println("Estatus: "+ est);
    }//GEN-LAST:event_btnAddPrestamoActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPrestamo;
    private javax.swing.JComboBox<String> cbLectores;
    private javax.swing.JComboBox<String> cbLibrosDisp;
    private javax.swing.JComboBox<String> cbSucursales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
