/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.ipn.dbst.ui;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author el pasito
 */
public class Biblioteca extends javax.swing.JPanel {

    /**
     * Creates new form Libro
     */
    public Biblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        texFieldNomSuc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldDireccion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bibliteca"));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Nombre sucursal: ");
        jPanel2.add(jLabel1);

        texFieldNomSuc.setText("jTextField1");
        texFieldNomSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFieldNomSucActionPerformed(evt);
            }
        });
        jPanel2.add(texFieldNomSuc);

        jLabel2.setText("Direccion:");
        jPanel2.add(jLabel2);

        textFieldDireccion.setText("jTextField2");
        jPanel2.add(textFieldDireccion);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Dar de alta");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                darAltaBiblioteca(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(mensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(mensaje)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    // Funcion que dara de alta la biblioteca
    private void darAltaBiblioteca(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_darAltaBiblioteca
        // validando que los campos no esten vacios
        if( (texFieldNomSuc.getText().length() > 0
            && textFieldDireccion.getText().length()>  0)){
            try {
                Connection connection = null;
                connection = Conexion.crearConexion();
                String query = "INSERT INTO sucursalBiblioteca(nombreSucursal,direccion) VALUES(?,?) ";
                PreparedStatement preparedStatement = connection.prepareStatement(query);
                preparedStatement.setString(1,texFieldNomSuc.getText());
                preparedStatement.setString(2,textFieldDireccion.getText());
                preparedStatement.execute();
                mensaje.setText("La Bibioteca "+ texFieldNomSuc.getText());
            } catch (SQLException ex) {
                Logger.getLogger(Biblioteca.class.getName()).log(Level.SEVERE, null, ex);
            }
    }else{ /// hay algun compo vacio
            mensaje.setText("uno de los campos requeridos esta vacio.. ");
            }
    }//GEN-LAST:event_darAltaBiblioteca

    private void texFieldNomSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFieldNomSucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFieldNomSucActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mensaje;
    private javax.swing.JTextField texFieldNomSuc;
    private javax.swing.JTextField textFieldDireccion;
    // End of variables declaration//GEN-END:variables
}
