/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.ipn.dbst.ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hector
 */
public class Editorial extends javax.swing.JPanel {

    /**
     * Creates new form Editorial
     */
    public Editorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        estado = new javax.swing.JLabel();
        AltaEditorial = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.BorderLayout(10, 10));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Alta editorial"));
        jPanel2.setMaximumSize(new java.awt.Dimension(154, 107));
        jPanel2.setMinimumSize(new java.awt.Dimension(154, 107));
        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1);

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel2.add(nombre);

        jLabel2.setText("Direccion:");
        jPanel2.add(jLabel2);

        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });
        jPanel2.add(direccion);

        jLabel3.setText("Telefono:");
        jPanel2.add(jLabel3);
        jPanel2.add(telefono);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        AltaEditorial.setText("Dar de alta");
        AltaEditorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AltaEditorialMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(AltaEditorial)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estado)
                    .addComponent(AltaEditorial))
                .addGap(0, 155, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void AltaEditorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AltaEditorialMouseClicked
        if ((nombre.getText().length() > 0)
                && (direccion.getText().length() > 0)
                && (telefono.getText().length() > 0)) {
            Connection connection = null;
            //Statement statement = null;
            ResultSet resultSet = null;

            try {
                connection = Conexion.crearConexion();
                //statement = connection.createStatement();
                
                String query = "INSERT INTO editorial(editorialNom,direccion,telefono) VALUES (?,?,?)";
                PreparedStatement preparedStatement = connection.prepareStatement(query);
                preparedStatement.setString(1, nombre.getText());
                preparedStatement.setString(2, direccion.getText());
                preparedStatement.setInt(3, Integer.valueOf(telefono.getText()));
                preparedStatement.execute();
                estado.setText(nombre.getText() + " dado de alta con exito");
                        
            } catch (SQLException ex) {
                Logger.getLogger(Editorial.class.getName()).log(Level.SEVERE, null, ex);
                estado.setText(ex.getMessage());
            } 
                
                    //resultSet.close();
                    
                    //connection.close();
                
            

        } else {
            estado.setText("uno de los campos requeridos esta vacio");
        }
    }//GEN-LAST:event_AltaEditorialMouseClicked

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AltaEditorial;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
