/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.ipn.dbst.ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author hector
 */
public class Libro extends javax.swing.JPanel {

    /**
     * Creates new form Libro
     */
    public Libro() {
        initComponents();
        listaEditoriales();
        
    }

    private void listaEditoriales() {
            Connection connection = null;
            ResultSet resultSet = null;
            Statement statement = null;
            String resultados = new String();

            try {
                connection = Conexion.crearConexion();
                statement = connection.createStatement();
                resultSet = statement.executeQuery("SELECT editorialNom FROM editorial");
                while (resultSet.next()) {
                    resultados += resultSet.getString("editorialNom") + ", ";
                }
                editorial.setModel(new DefaultComboBoxModel(resultados.split(", ")));
                //Conexion.close();
            } catch (SQLException ex) {
                Logger.getLogger(Libro.class.getName()).log(Level.SEVERE, null, ex);
            }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        editorial = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        AltaLibro = new javax.swing.JButton();
        estado = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Libro"));
        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Titulo:");
        jPanel2.add(jLabel1);
        jPanel2.add(titulo);

        jLabel2.setText("Editorial:");
        jPanel2.add(jLabel2);

        editorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        editorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorialActionPerformed(evt);
            }
        });
        jPanel2.add(editorial);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        AltaLibro.setText("Dar de alta libro");
        AltaLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AltaLibroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(AltaLibro)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AltaLibro)
                    .addComponent(estado)
                    .addComponent(mensaje))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void editorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editorialActionPerformed

    private void AltaLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AltaLibroMouseClicked
        Connection connection = null;            
        ResultSet resultSet = null;
        PreparedStatement preparedStatement;
        String query;
        
        if(titulo.getText().length() > 0){
            try {
                connection = Conexion.crearConexion();
                query = "INSERT INTO libro(titulo,editorialNom) VALUES (?,?)";
                preparedStatement = connection.prepareStatement(query);
                preparedStatement.setString(1, titulo.getText());
                preparedStatement.setString(2, editorial.getSelectedItem().toString());
                preparedStatement.execute();
                mensaje.setText("se da de alta: " + titulo.getText() 
                        + "en editorial " 
                        + editorial.getSelectedItem().toString());
                
            } catch (SQLException ex) {
                Logger.getLogger(Libro.class.getName()).log(Level.SEVERE, null, ex);
                mensaje.setText(ex.getMessage());
            }
        }
    }//GEN-LAST:event_AltaLibroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AltaLibro;
    private javax.swing.JComboBox<String> editorial;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mensaje;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
