/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.ipn.dbst.ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author hector
 */
public class LibroBaja extends javax.swing.JPanel {

    /**
     * Creates new form Libro
     */
    public LibroBaja() {
        initComponents();
        listaLibros();
        //listaEditoriales();

    }

    private void listaEditoriales() {
        Connection connection = null;
        ResultSet resultSet = null;
        Statement statement = null;
        String resultados = new String();
        String query = new String("SELECT editorialNom FROM libro WHERE titulo=\"");
        
        try {
            connection = Conexion.crearConexion();
            statement = connection.createStatement();
            query += titulo.getSelectedItem().toString() + "\"";
            resultSet = statement.executeQuery(query);
            while (resultSet.next()) {
                resultados += resultSet.getString("editorialNom") + ", ";
            }
            editorial.setModel(new DefaultComboBoxModel(resultados.split(", ")));
            //Conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(LibroBaja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void listaLibros() {
        Connection connection = null;
        ResultSet resultSet = null;
        Statement statement = null;
        String resultados = new String();

        try {
            connection = Conexion.crearConexion();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("SELECT titulo FROM libro");
            while (resultSet.next()) {
                resultados += resultSet.getString("titulo") + ", ";
            }
            titulo.setModel(new DefaultComboBoxModel(resultados.split(", ")));
            editorial.setEnabled(true);
            listaEditoriales();
            //Conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(LibroBaja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        editorial = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        libroBaja = new javax.swing.JButton();
        estado = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Libro"));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Titulo:");
        jPanel2.add(jLabel1);

        titulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione un libro" }));
        titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tituloMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tituloMousePressed(evt);
            }
        });
        titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloActionPerformed(evt);
            }
        });
        jPanel2.add(titulo);

        jLabel2.setText("Editorial:");
        jPanel2.add(jLabel2);

        editorial.setEnabled(false);
        jPanel2.add(editorial);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        libroBaja.setText("Dar de baja libro");
        libroBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libroBajaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(libroBaja)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libroBaja)
                    .addComponent(estado)
                    .addComponent(mensaje))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloActionPerformed
        
    }//GEN-LAST:event_tituloActionPerformed

    private void libroBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libroBajaMouseClicked
       Connection connection = null;            
        ResultSet resultSet = null;
        PreparedStatement preparedStatement;
        String query;
        
        
        
        
            try {
                connection = Conexion.crearConexion();
                query = "DELETE FROM libro WHERE titulo=?";
                preparedStatement = connection.prepareStatement(query);
                preparedStatement.setString(1, titulo.getSelectedItem().toString());
                preparedStatement.execute();
                mensaje.setText("se da de baja: " + titulo.getSelectedItem().toString()
                        + "en editorial " 
                        + editorial.getSelectedItem().toString());
                listaLibros();
                
            } catch (SQLException ex) {
                Logger.getLogger(LibroAlta.class.getName()).log(Level.SEVERE, null, ex);
                mensaje.setText(ex.getMessage());
            }
        
    }//GEN-LAST:event_libroBajaMouseClicked

    private void tituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseClicked
        //listaLibros();
    }//GEN-LAST:event_tituloMouseClicked

    private void tituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMousePressed
        //listaLibros();
    }//GEN-LAST:event_tituloMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> editorial;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton libroBaja;
    private javax.swing.JLabel mensaje;
    private javax.swing.JComboBox<String> titulo;
    // End of variables declaration//GEN-END:variables
}
