/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.ipn.dbst.ui;

import java.awt.BorderLayout;
import java.awt.MenuBar;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author angeldlr
 */
public class mainView extends javax.swing.JFrame {

    /**
     * Creates new form mainView
     */
    public mainView() {
        initComponents();
        iniciaMenuBar();
    }

    
    private void iniciaMenuBar(){
        JMenuItem Editorial = new JMenuItem("Editorial");
        JMenuItem Autor = new JMenuItem("Autor");
        JMenuItem Libro = new JMenuItem("Libro");
        JMenuItem Biblioteca = new JMenuItem("Biblioteca");
        
        Editorial.setActionCommand("E");
        Autor.setActionCommand("A");
        Libro.setActionCommand("L");
        Biblioteca.setActionCommand("B");
        
        Editorial.setMnemonic(KeyEvent.VK_E);
        Autor.setMnemonic(KeyEvent.VK_A);
        Libro.setMnemonic(KeyEvent.VK_L);
        Biblioteca.setMnemonic(KeyEvent.VK_B);
        
        Editorial.addActionListener(new ListenerMenus());
        Autor.addActionListener(new ListenerMenus());
        Libro.addActionListener(new ListenerMenus());
        Biblioteca.addActionListener(new ListenerMenus());
        
        jMenu3.setMnemonic(KeyEvent.VK_A);
        jMenu3.add(Editorial);
        jMenu3.add(Autor);
        jMenu3.add(Libro);
        jMenu3.add(Biblioteca);   
    }
    
    class ListenerMenus implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            String opcion = e.getActionCommand();
            JPanel panel = null;
            switch(opcion){
                case "E":                    
                    panel = new Editorial();
                    break;
                case "L":
                    panel = new Libro();
                    break;
                case "A":
                    panel = new Autor();
                    break;
                case "B":
                    panel = new Biblioteca();
                    break;
                    
            }
            getContentPane().removeAll();
            add(panel,BorderLayout.CENTER);
            pack();
            validate();
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(20, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu3.setText("Altas");
        MenuBar.add(jMenu3);

        jMenu4.setText("Bajas");
        MenuBar.add(jMenu4);

        setJMenuBar(MenuBar);
        MenuBar.getAccessibleContext().setAccessibleName("menuBar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Conexion a = new Conexion();
        try {
            a.crearConexion();
        } catch (SQLException ex) {
            Logger.getLogger(mainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
