/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.ipn.dbst.ui;

import ipn.mx.dbst.controlador.PrestamoCon;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.ipn.dbst.model.*;

/**
 *
 * @author angeldlr
 */
public class mainView extends javax.swing.JFrame {

    /**
     * Creates new form mainView
     */
    public mainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelLibros = new javax.swing.JPanel();
        panelSucursales = new javax.swing.JPanel();
        panelLectores = new javax.swing.JPanel();
        panelPrestamos = new javax.swing.JPanel();
        btnPrestamo = new javax.swing.JButton();
        btnVPrestamos = new javax.swing.JButton();
        btnDevolucion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 600));

        javax.swing.GroupLayout panelLibrosLayout = new javax.swing.GroupLayout(panelLibros);
        panelLibros.setLayout(panelLibrosLayout);
        panelLibrosLayout.setHorizontalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );
        panelLibrosLayout.setVerticalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("LIBROS", panelLibros);

        javax.swing.GroupLayout panelSucursalesLayout = new javax.swing.GroupLayout(panelSucursales);
        panelSucursales.setLayout(panelSucursalesLayout);
        panelSucursalesLayout.setHorizontalGroup(
            panelSucursalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );
        panelSucursalesLayout.setVerticalGroup(
            panelSucursalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SUCURSALES", panelSucursales);

        javax.swing.GroupLayout panelLectoresLayout = new javax.swing.GroupLayout(panelLectores);
        panelLectores.setLayout(panelLectoresLayout);
        panelLectoresLayout.setHorizontalGroup(
            panelLectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );
        panelLectoresLayout.setVerticalGroup(
            panelLectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("LECTORES", panelLectores);

        btnPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamoActionPerformed(evt);
            }
        });

        btnVPrestamos.setMaximumSize(new java.awt.Dimension(140, 27));
        btnVPrestamos.setMinimumSize(new java.awt.Dimension(140, 27));
        btnVPrestamos.setPreferredSize(new java.awt.Dimension(140, 27));
        btnVPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVPrestamosActionPerformed(evt);
            }
        });

        btnDevolucion.setMaximumSize(new java.awt.Dimension(140, 27));
        btnDevolucion.setMinimumSize(new java.awt.Dimension(140, 27));
        btnDevolucion.setPreferredSize(new java.awt.Dimension(140, 27));
        btnDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrestamosLayout = new javax.swing.GroupLayout(panelPrestamos);
        panelPrestamos.setLayout(panelPrestamosLayout);
        panelPrestamosLayout.setHorizontalGroup(
            panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestamosLayout.createSequentialGroup()
                .addGroup(panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrestamosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelPrestamosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE))
                    .addGroup(panelPrestamosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPrestamosLayout.setVerticalGroup(
            panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("PRESTAMOS", panelPrestamos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoActionPerformed
        RealizarPrestamoView wp = new RealizarPrestamoView();
        wp.setVisible(true);
        wp.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnPrestamoActionPerformed

    private void btnDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionActionPerformed
        List<Lector> listLectores = null;
        
        PrestamoCon querySuc = new PrestamoCon();
        Connection con = querySuc.getConection();
        try {
            listLectores = querySuc.getLectores(con);
        } catch (SQLException ex) {
            Logger.getLogger(RealizarPrestamoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] lectoresPrestamo = new String[listLectores.size()];
        for(int i=0;i<listLectores.size();i++){
            int numL= listLectores.get(i).getNumTarjeta();
            String nom = listLectores.get(i).getNombre();
            lectoresPrestamo[i] = String.valueOf(numL);
        }
        String lector =  (String)JOptionPane.showInputDialog(null,"Seleccione el lector que hara la devolución",
                "Lectores", JOptionPane.DEFAULT_OPTION,null,lectoresPrestamo,lectoresPrestamo[0]);
        try {
            List<String[]> prestamos = querySuc.getLecPrestamos(con,new Lector(Integer.parseInt(lector),null,null,null));
        } catch (SQLException ex) {
            Logger.getLogger(mainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDevolucionActionPerformed

    private void btnVPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVPrestamosActionPerformed
        MostrarPrestamosView presview = new MostrarPrestamosView();
        presview.setVisible(true);
        presview.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btnPrestamo;
    private javax.swing.JButton btnVPrestamos;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelLectores;
    private javax.swing.JPanel panelLibros;
    private javax.swing.JPanel panelPrestamos;
    private javax.swing.JPanel panelSucursales;
    // End of variables declaration//GEN-END:variables
}
